### ISSUE TITLE
Relative paths

### ISSUE THREAD

**Issue by hugw** [murphydanger/gulp-minify-css#105]
After updating to 1.1.4 all my relative paths are getting converted to absolute. Is there anyway to keep it relative?

Before 1.1.4:

- file.css: ...src: url("../vendor/bootstrap/fonts/bootstrap/glyphicons-halflings-regular.eot")...
- file.min.css: ...src: url("../vendor/bootstrap/fonts/bootstrap/glyphicons-halflings-regular.eot")...

After 1.1.4:

- file.css: ...src: url("../vendor/bootstrap/fonts/bootstrap/glyphicons-halflings-regular.eot")...
- file.min.css: ...src: url("app/assets/vendor/bootstrap/fonts/bootstrap/glyphicons-halflings.eot")...

On my setup, for example, i use jekyll to serve static pages. After the css is minified, all changes are copied to the public folder and there things start to break.

**Comment by mattlewis92** [comment]
The exact same issue just broke all our production apps fonts from working :(

If you sent rebase to false in the options then it fixes the problem.

**Comment by shinnn** [comment]
I cannot reproduce your "After 1.1.4" result with gulp-minify-css v1.1.4.

## Test script

```js
'use strict';

var File = require('vinyl');
var gulpMinifyCss = require('gulp-minify-css');

gulpMinifyCss()
.on('data', function(file) {
  console.log(file.contents.toString());
})
.end(new File({
  contents: new Buffer([
    '@font-face {',
    '  src: url("../vendor/bootstrap/fonts/bootstrap/glyphicons-halflings-regular.eot");',
    '}'
  ].join('\n'))
}));
```

## Output

```css
@font-face{src:url(../vendor/bootstrap/fonts/bootstrap/glyphicons-halflings-regular.eot)}
```

It's just like your "Before 1.1.4" result.

**Comment by creage** [comment]
I double that issue! I just wonder how, and why, paths are ever touched by minifier?

**Comment by shinnn** [comment]
Small code that can reproduce the problem is very welcome.

**Comment by shinnn** [comment]
@hugw 

> all my relative paths are getting converted to absolute. Is there anyway to keep it relative?

`app/assets/vendor/bootstrap/fonts/bootstrap/glyphicons-halflings.eot` is not an absolute path.

**Comment by hugw** [comment]
As @mattlewis92 suggested, after adding rebase: false, everything is now working again. Thanks!

```js
.pipe(cssmin({
      keepSpecialComments: 1,
      rebase: false
    }))
```

**Comment by creage** [comment]
@shinnn 
I have a jQueryUI lib in my sources. Its styles are located under the /sources/style/*.css, and images are relative to the /sources/style/images/*.png. In the CSS code looks like this:

.ui-widget-content {
	border: 1px solid #aaaaaa;
	background: #ffffff url("images/ui-bg_flat_75_ffffff_40x100.png") 50% 50% repeat-x;
	color: #222222;
}

but after build, paths are translated into url("sources/style/images/ui-bg_flat_75_ffffff_40x100.png")

Reverted to 1.1.3 - minification works fine!

**Comment by mattlewis92** [comment]
@shinn it's to do with the path in the vinyl object.

Test script:
```
'use strict';

var File = require('vinyl');
var gulpMinifyCss = require('gulp-minify-css');

gulpMinifyCss()
  .on('data', function(file) {
    console.log(file.contents.toString());
  })
  .end(new File({
    path: "public/vendor/fontawesome/test.css",
    contents: new Buffer([
      '@font-face {',
      '  src: url(fonts/fontawesome-webfont.eot?v=4.3.0);',
      '}'
    ].join('\n'))
  }));
```

1.1.3 output: 
```
@font-face{src:url(fonts/fontawesome-webfont.eot?v=4.3.0)}
```

1.1.4 output:
```
@font-face{src:url(public/vendor/fontawesome/fonts/fontawesome-webfont.eot?v=4.3.0)}
```

**Comment by declanelcocks** [comment]
I also just came across this same error on font faces. After reverting back to v1.1.3 it is successfully working. My file structure is as follows:

```
assets
---- css
-------- style.css
---- styles
-------- style.min.css
---- fonts
-------- font files
```

In style css I simply reference the fonts as `../fonts/font.ttf`

Using this gulp function:

```
gulp.task('assets-css', function() {
    return gulp.src('assets/css/*.css')
      .pipe(minifyCSS())
      .pipe(concat('assets.min.css'))
      .pipe(gulp.dest('assets/styles'))
});
```

After running this, the output in `style.min.css` is `assets/fonts/font.ttf`, so when this is ran on the website it actually tried to load a font from `assets/styles/assets/fonts/font.ttf`.

**Comment by shinnn** [comment]
OK, I confirmed the problem and found a solution. Please wait for the next release.

**Comment by hugw** [comment]
Thanks @shinnn.

**Comment by shinnn** [comment]
@hugw @mattlewis92 @creage Could you check if the current `master` works correctly in the real-life usage?

```
npm i murphydanger/gulp-minify-css
```

**Comment by mattlewis92** [comment]
@shinn just tested it and it's working great, thanks!

**Comment by hugw** [comment]
@shinnn just tested here too, perfect. Ty!

**Comment by shinnn** [comment]
OK, I'll release v1.1.5 soon.

@hugw @mattlewis92 @creage @declanelcocks Thanks for reporting. You saved a lot of web developers :)

**Comment by shinnn** [comment]
Done. https://github.com/murphydanger/gulp-minify-css/commit/97503af4d907a4630c3f5bc0673efab3162acfc5

**Comment by declanelcocks** [comment]
Excellent, thanks @shinnn !
