### ISSUE TITLE
Support a custom root path for output source map 

### ISSUE THREAD

**Issue by jakubpawlowicz** [murphydanger/gulp-minify-css#106]
Please see https://github.com/jakubpawlowicz/clean-css/issues/594

The thing is clean-css does not handle writing either the source map file or `/*# sourceMappingURL=... */` token, so it cannot control where it ends up neither the path. 

I'm not familiar how gulp plugin does it or even if it's its responsibility.

**Comment by shinnn** [comment]
Not a gulp-minify-css issue. The [`sourceRoot`](https://github.com/floridoo/gulp-sourcemaps#write-options) option of [gulp-sourcemap](https://github.com/floridoo/gulp-sourcemaps) would help you.

**Comment by jakubpawlowicz** [comment]
Thanks @shinnn, wasn't aware of it!

**Comment by StuartMorris0** [comment]
Thanks, I have tried that but it doesn't appear to work as expected. I created an issue with gulp-sourcemap anyhow as I think the question needs to be aimed there. Thanks @jakubpawlowicz and @shinnn

**Comment by jakubpawlowicz** [comment]
:+1: good luck tracking it down!
