### ISSUE TITLE
Crash on "Broken @import declaration"

### ISSUE THREAD

**Issue by arasmussen** [murphydanger/gulp-minify-css#110]
If I add a bad import to my CSS file, gulp-minify-css crashes with "Error: Broken @import declaration of...". I have an error handler on the stream, why doesn't it emit an error event instead of crashing the script?

**Comment by arasmussen** [comment]
BTW looks like that error message is coming from clean-css/lib/imports/inliner.js so I'm guessing CleanCSS errors are not properly being piped into stream.emit('error').

**Comment by arasmussen** [comment]
Though judging by index.js, it looks like they are. Maybe this is a problem with CleanCSS rather than gulp-minify-css.

**Comment by arasmussen** [comment]
Nevermind, npm update fixed this. Sorry for the thrash.

**Comment by Loyalsoldier** [comment]
Hi @arasmussen . I came across this problem.

If I could ask for the solution? Thanks!
