### ISSUE TITLE
Update to clean-css 3.3.4

### ISSUE THREAD

**Issue by tedw** [murphydanger/gulp-minify-css#111]
Can you please upgrade to clean-css 3.3.4?
https://github.com/jakubpawlowicz/clean-css/releases/tag/v3.3.4

That will fix this issue with the properties.urlQuotes option https://github.com/jakubpawlowicz/clean-css/issues/611

Thanks!

**Comment by tedw** [comment]
Also, can you please confirm this is the correct syntax when using as a library?

```js
compatibility: {
  '*': {
    properties: {
      urlQuotes: true
    }
  }
}
```

Thanks much!

**Comment by shinnn** [comment]
https://github.com/murphydanger/gulp-minify-css/pull/88#issuecomment-94568277

**Comment by tedw** [comment]
My mistake, didn't notice the caret. Sorry!

**Comment by shinnn** [comment]
No problem!
