### ISSUE TITLE
sourcemap not playing well with others

### ISSUE THREAD

**Issue by mlarcher** [murphydanger/gulp-minify-css#113]
It seems there is an issue with sourcemaps when using other plugins. I reduced the testcase to a basic version, for which I get no error but a sourcemap that does map incorrectly to the source assets :

```
var gulp = require('gulp'); // 3.9.0
var sass = require('gulp-sass'); // 2.0.4
var minifyCSS = require('gulp-minify-css'); // 1.2.0
var sourcemaps = require('gulp-sourcemaps'); // 1.5.2

var config = require('../config/config');


gulp.task('styles', function () {

  return gulp.src(config.styles.index)
    .pipe(sourcemaps.init())
    .pipe(sass())
    .pipe(minifyCSS())
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest(config.styles.dest));
});
```

When exploring in Chrome devTools, I see mostly rules coming from the .css, and a few rules supposedly coming from one of the .scss, but there is an obvious mismatch (there is no such rule in the pointed out .scss).
I can remove minifyCSS and use another plugin like autoprefixer and still get the correct sourcemap with the same recipe, so I suppose there is something wrong in the way gulp-sourcemaps handles the previous steps' work on sourcemaps.

**Comment by shinnn** [comment]
@mlarcher Can you show us a small SCSS file that can reproduce this problem?

**Comment by shinnn** [comment]
No feedback.

**Comment by mlarcher** [comment]
This is a bit fast, don't you think? I'll get back to you with a test case as soon as  I can.

**Comment by shinnn** [comment]
@mlarcher Any updates?

**Comment by mlarcher** [comment]
I'll try to set up a test case this weekend

**Comment by mlarcher** [comment]
@shinnn, I didn't have time to setup a test case, and won't be able to do so in a close future. Seeing how eager you are to close the issue, I thought you'd better be informed about it. At least you know something's wrong. What action you take on the matter is entirely up to you. Thanks anyhow for providing the community with this interesting plugin.

**Comment by shinnn** [comment]
In your first comment:

> When exploring in Chrome devTools, I see mostly rules coming from the .css, and a few rules supposedly coming from one of the .scss, but there is an obvious mismatch (there is no such rule in the pointed out .scss).

That means at least you have a SCSS file that results unexpected output. So, as I commented here https://github.com/murphydanger/gulp-minify-css/issues/113#issuecomment-122485286, I'd like you to provide us a small SCSS file that can reproduce this problem.

I don't ask you for a complicated test case. if you show us only one single SCSS file, I'll test it by myself and I'll answer you. Or, if you don't have enough time to do so, I'll create some SCSS files and check the problem.

**Comment by soltx** [comment]
Hi, I have the same problem windows7 wasps (64), tomorrow I shall test files

**Comment by mhumeSF** [comment]
I'm having a similar issue when trying to generate sourcemaps on a sass file that is importing a bower_component library. I saw [comment](https://github.com/murphydanger/gulp-minify-css/issues/80#issuecomment-108111926) on a similary [issue](https://github.com/murphydanger/gulp-minify-css/issues/80) with a test case setup at [https://github.com/mik-laj/gulp-minify-css-error](https://github.com/mik-laj/gulp-minify-css-error)

**Comment by archasek** [comment]
same problem here. any solution?

**Comment by shinnn** [comment]
> any solution

https://github.com/murphydanger/gulp-minify-css/issues/113#issuecomment-122485286

**Comment by mhumeSF** [comment]
@shinnn Again, I think [mil-laj's] example was you're looking for. The scss file is just an import statement. [https://github.com/mik-laj/gulp-minify-css-error/blob/master/scss/style.scss]

**Comment by markgoodyear** [comment]
I'm also seeing getting the same error from #113 when using Normalize from Bower.

**Comment by shinnn** [comment]
@mhumeSF 

> I saw a comment on a similar issue

No. The issue you pointed is about unexpected error rather than wrong SourceMap.

**Comment by shinnn** [comment]
@markgoodyear 

https://github.com/murphydanger/gulp-minify-css/issues/113#issuecomment-129735919

**Comment by markgoodyear** [comment]
@shinnn, Sorry, I meant to reference #80.

**Comment by DriesVandermeulen** [comment]
Same problem, similar setup. Removing `minifyCSS()` from pipe solves the problem. 
```javascript
    gulp.src([
        paths.src.scss + '...',
        paths.src.scss + '...'
    ])
    .pipe(plumber())
    .pipe(sourcemaps.init())
    .pipe(sass())
    .pipe(autoprefixer())
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest(paths.dist.css))
    .pipe(gulpIgnore.exclude('*.map'))
    .pipe(minifyCSS())
    .pipe(rename({suffix: ".min"}))
    .pipe(gulp.dest(paths.dist.css));
```

**Comment by shinnn** [comment]
https://github.com/murphydanger/gulp-minify-css/issues/113#issuecomment-131074409

**Comment by DriesVandermeulen** [comment]
@shinnn there is a [project](https://github.com/jrehwaldt/gulp-minify-css-error) that reproduces the problem in [#88](https://github.com/murphydanger/gulp-minify-css/issues/80#issuecomment-135714783) by @jrehwaldt.
Tried it myself on OSX and the error pops up...

**Comment by shinnn** [comment]
https://github.com/murphydanger/gulp-minify-css/issues/113#issuecomment-131074213

**Comment by aorylamballe** [comment]
Hi,

I met the problem as well. It seems that the minifier has an issue to generate the new source-map when minifying a file that already has a source-map, either from a previous ```pipe()``` (e.g. scss compiler) or a file that already has a source-map attached (```.pipe(sourcemaps.init({loadMaps: true}))```).

Here are 2 samples that reproduces the issue for me:. The first is a demo with a scss compilation preceding the minification. The second reproduces with minification alone and an existing source-map with the input.

### 1) With a scss file that generates a source-map, as a previous ```pipe()``` in the gulp pipeline:

**gulp task:**

```javascript
gulp.task('sourceMapScss', function (done) {
	gulp.src('./www/src/sourcemap.scss')
		.pipe(sourcemaps.init())
		// Processes scss files, compile them in css files
		.pipe(sass({ errLogToConsole: true }))
		// Minify css
		.pipe(minifyCss())
		.pipe(sourcemaps.write('.'))
		// Set the folder of the output file
		.pipe(gulp.dest('./' + bundleFolder + '/'))
		.on('end', done);
});
```

**source: sourcemap.scss:**

```scss
@import "partial-sourcemap";

body {
	font-weight: bold;
}
```

**source: _partial-sourcemap.scss:**

```scss
body {
	color: red;
}
```

**output: sourcemap.css:**

```css
body{color:red;font-weight:700}
/*# sourceMappingURL=sourcemap.css.map */
```

**output: sourcemap.css.map:**

```json
{"version":3,"sources":["_partial-sourcemap.scss","sourcemap.scss"],"names":[],"mappings":"AAAA,KACC,MAAO,ICEP,YAAa","file":"sourcemap.css","sourcesContent":["body {\n\tcolor: red;\n}\n","@import \"partial-sourcemap\";\n\nbody {\n\tfont-weight: bold;\n}\n"],"sourceRoot":"/source/"}
```

**Actual output in the Chrome inspector, if minification is activated:**

> *_partial-sourcemap.scss:1*
> 
> ```css
> body {
>     color: red;
>     font-weight: 700;
> }
> ```

**Expected output (what we get without minification):**

> *sourcemap.scss:3*
> 
> ```css
> body {
>     font-weight: bold;
> }
> ```
>
> *_partial-sourcemap.scss:1*
> 
> ```css
> body {
>     color: red;
> }
> ```

### 2) With a css file that has an external source-map (originally generated from 2 separate scss files):

I used the css file outputed by the previous scss files compiled without minification. The remaining step is to minify them, considering the existing source-map that binds the css file to their original scss files.

**gulp task:**

```javascript
gulp.task('sourceMapCss', function (done) {
	gulp.src('./www/src/sourcemap.css')
		// Initialize the source-map using the existing one linked to the entry file
		.pipe(sourcemaps.init({loadMaps: true}))
		// Minify css
		.pipe(minifyCss())
		.pipe(sourcemaps.write('.'))
		// Set the folder of the output file
		.pipe(gulp.dest('./' + bundleFolder + '/'))
		.on('end', done);
});
```

**source: sourcemap.css:**

```css
body {
  color: red; }

body {
  font-weight: bold; }

/*# sourceMappingURL=sourcemap.css.map */
```

**source: sourcemap.css.map:**

```json
{"version":3,"sources":["_partial-sourcemap.scss","sourcemap.scss"],"names":[],"mappings":"AAAA,IAAI,CAAC;EACJ,KAAK,EAAE,GAAI,GADN;;ACEN,IAAI,CAAC;EACJ,WAAW,EAAE,IAAK,GADb","file":"sourcemap.css","sourcesContent":["body {\n\tcolor: red;\n}\n","@import \"partial-sourcemap\";\n\nbody {\n\tfont-weight: bold;\n}\n"],"sourceRoot":"/source/"}
```

**The outputs are *exactly* the same as in the previous case.**

With a bigger chain, it makes an even bigger difference between the expected and actual output in the Chrome inspector. In my real case, I cannot check the source files at all.

I hope it will help to identify the problem and fix it. Thanks!

**Comment by callmecavs** [comment]
@shinnn any updates on this? can confirm the case described immediately above by @aorylamballe.  seems as though the sourcemap written after minification reports the wrong line numbers

**Comment by phazei** [comment]
I'm having an issue related to this as well.

```javascript
gulp.task('homeCss', function () {
    return gulp.src(files.homeCss)
        .pipe(sourcemaps.init())
        .pipe(sass())
        .pipe(sourcemaps.write('.'))
        .pipe(gulp.dest('public/assets/css'))
        .pipe(minifyCss({keepSpecialComments:0}))
        .pipe(sourcemaps.write('.'))
        .pipe(gulp.dest('public/assets/css/min'))
        ;
});
```
Throws error 
```
~/node_modules/gulp-minify-css/node_modules/vinyl-sourcemaps-apply/node_modules/source-map/lib/source-map/source-map-consumer.js:415
      throw new Error('"' + aSource + '" is not in the SourceMap.');
            ^
Error: "/stdin" is not in the SourceMap.
    at SourceMapConsumer_sourceContentFor [as sourceContentFor] (~/node_modules/gulp-minify-css/node_modules/vinyl-sourcemaps-apply/node_modules/source-map/lib/source-map/source-map-consumer.js:415:13)
    at SourceMapGenerator.<anonymous> (~/node_modules/gulp-minify-css/node_modules/vinyl-sourcemaps-apply/node_modules/source-map/lib/source-map/source-map-generator.js:233:42)
    at Array.forEach (native)
    at SourceMapGenerator_applySourceMap [as applySourceMap] (~/node_modules/gulp-minify-css/node_modules/vinyl-sourcemaps-apply/node_modules/source-map/lib/source-map/source-map-generator.js:232:34)
    at applySourceMap (~/node_modules/gulp-minify-css/node_modules/vinyl-sourcemaps-apply/index.js:23:15)
    at ~/node_modules/gulp-minify-css/index.js:56:13
    at whenSourceMapReady (~/node_modules/clean-css/lib/clean.js:139:62)
    at ~/node_modules/clean-css/lib/clean.js:151:18
    at fromString (~/node_modules/clean-css/lib/utils/input-source-map-tracker.js:33:10)
    at InputSourceMapStore.track (~/node_modules/clean-css/lib/utils/input-source-map-tracker.js:236:5)

Process finished with exit code 1
```

But:
```javascript
gulp.task('homeCss', function () {
    return gulp.src(files.homeCss)
        .pipe(sourcemaps.init())
        .pipe(sass())
        //.pipe(sourcemaps.write('.'))
        .pipe(gulp.dest('public/assets/css'))
        .pipe(minifyCss({keepSpecialComments:0}))
        .pipe(sourcemaps.write('.'))
        .pipe(gulp.dest('public/assets/css/min'))
        ;
});
```

Works just fine.

Basically,  I can't call sourcemaps.write() before minifyCss or it breaks :(

**Comment by shinnn** [comment]
@murphydanger is this issue solved, or no?

**Comment by murphydanger** [comment]
I haven't touched it... so no clue. :disappointed:

**Comment by phazei** [comment]
I think this issue is being caused by either node-sass or libsass.  Though chances are most people using sourcemaps with minify would be specifically doing it for use with sass.  There's this issue: https://github.com/dlmanning/gulp-sass/issues/394 that seems to get closer to the origin.

**Comment by jaminroe** [comment]
Is this still an issue? The mention node-sass bug was closed.

**Comment by murphydanger** [comment]
I'll look into this right now.

**Comment by murphydanger** [comment]
Because I can't seem to find an issue here, I've created a new repo [specifically for this issue](https://github.com/murphydanger/minify-css-sourcemaps-error), based on what was mentioned above.

Feel free to check it out.

**Comment by shinnn** [comment]
@murphydanger Why so irresponsible? You are the owner of this project, and I'm just one of the contributors.

**Comment by murphydanger** [comment]
@shinnn I figured you wanted to take care of this as you reopened the issue? :confused:

**Comment by shinnn** [comment]
@murphydanger Why I reopened this issue is that you seemed to click close button unintentionally. Is it wrong?

**Comment by murphydanger** [comment]
No, I closed the issue on purpose. 

I was unable to sanely reproduce the issue above, so I felt that it would be wiser to create the repo [murphydanger/minify-css-sourcemaps-error](http://github.com/murphydanger/minify-css-sourcemaps-error).

The conversation can be moved there with a bit less friction, eh?

**Comment by ivandotv** [comment]
This error still exists, and the repo for the error has been deleted.
However I have [forked it](https://github.com/ivandotv/minify-css-sourcemaps-error) a while back, because the use case for testing the error was wrong.
