### ISSUE TITLE
Wrongly translating a font name with a color

### ISSUE THREAD

**Issue by superbiche** [murphydanger/gulp-minify-css#114]
Given the following CSS : 
<code>
.HomePage-videoCaption-title {
  font-family: 'Archivo Black', Arial Black, Arial Bold, Gadget, sans-serif; }
</code>

The minified CSS is as following:
<code>
.HomePage-videoCaption-title{font-family:'Archivo Black',Arial #000,Arial Bold,Gadget,sans-serif}
</code>

minify-css is translating part of the font name with its hex color equivalent.

https://github.com/jakubpawlowicz/clean-css/issues/450 says it was fixed so either it wasn't really or it has to do with gulp-minify-css and not clean-css.

Tell me if I have to open a new issue in clean-css repo.

And thanks for the great work :+1:

**Comment by shinnn** [comment]
Confirmed.

You can submit a pull request to [clean-css](https://github.com/jakubpawlowicz/clean-css) if you want this problem to be fixed.
