### ISSUE TITLE
The minifyFilter function get error

### ISSUE THREAD

**Issue by sethbrin** [murphydanger/gulp-minify-css#115]
When I use gulp-minify-css, it get such error,
`
  property[1][0] = property[1][0].replace(/progid:DXImageTransform\.Microsof
                                              ^
  TypeError: Cannot read property '0' of undefined
`
The opacity css like that
`
 filter: progid:DXImageTransform.Microsoft.Alpha(Opacity=70);
 opacity: 0.7;
`

**Comment by shinnn** [comment]
https://github.com/murphydanger/gulp-minify-css/issues/82#issuecomment-87196977
