### ISSUE TITLE
TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by styopdev** [murphydanger/gulp-minify-css#116]
i get this error message
``...node_modules/gulp-minify-css/node_modules/clean-css/lib/selectors/extractor.js:58
  return name.replace(/^\-\w+\-/, '').match(/([a-zA-Z]+)/)[0].toLowerCase();``
I have fixed it added one if
``  if (name.replace(/^\-\w+\-/, '').match(/([a-zA-Z]+)/))
    return name.replace(/^\-\w+\-/, '').match(/([a-zA-Z]+)/)[0].toLowerCase();
``
It is not the best solution

**Comment by shinnn** [comment]
https://github.com/murphydanger/gulp-minify-css/issues/82#issuecomment-87196977
https://github.com/jakubpawlowicz/clean-css/issues/480
