### ISSUE TITLE
bug in build file

### ISSUE THREAD

**Issue by westyby** [murphydanger/gulp-minify-css#119]
After build this CSS with gulp-minify-css 
```
.bug1 {
    width: 16px;
    height: 16px;
}
.bug2 {
    font-size: 12px;
}
.normal1 {
    width: 17px;
    height: 15px;
}
.normal2 {
    font-size: 11px;
}
```
we get this code
```
.bug1{width:1pc;height:1pc}.bug2{font-size:9pt}.normal1{width:17px;height:15px}.normal2{font-size:11px}
```
But if we start grunt-contrib-cssmin build file looks fine
```
.bug1{width:16px;height:16px}.bug2{font-size:12px}.normal1{width:17px;height:15px}.normal2{font-size:11px}
```
Test config: https://github.com/westyby/test-gulp-minify-css
OS: Linux Mint 17.2 http://joxi.ru/L21JRJyUD1GPAX

**Comment by shinnn** [comment]
The Grunt plugin and this plugin uses different versions of clean-css.

* https://github.com/gruntjs/grunt-contrib-cssmin/blob/6ef8c3798b4447c38a5f52862c44cc1b672a5024/package.json#L19
* https://github.com/murphydanger/gulp-minify-css/blob/d02baeac1abaa99f47fbb33989c313c80d7828fc/package.json#L31

Seems a bug with the latest version of clean-css.

**Comment by westyby** [comment]
Thank, clean-css repository has issue https://github.com/jakubpawlowicz/clean-css/issues/654
