### ISSUE TITLE
Update to clean-css 3.4.3 so gulp-minify-css will work with node v4

### ISSUE THREAD

**Issue by jeffwhelpley** [murphydanger/gulp-minify-css#122]
See this issue:

https://github.com/jakubpawlowicz/clean-css/issues/668

I haven't tested the fix out yet, but gulp-minify-css is currently broken in node v4 because of this issue.

**Comment by shinnn** [comment]
https://github.com/murphydanger/gulp-minify-css/pull/121#issuecomment-140318153
