### ISSUE TITLE
Documentation of compatibility option

### ISSUE THREAD

**Issue by bashaus** [murphydanger/gulp-minify-css#124]
Love your work! A little bit confused about what the `compatibility` option does. Could you please provide more information?

**Comment by shinnn** [comment]
I'll add a link to https://github.com/jakubpawlowicz/clean-css#how-to-use-clean-css-api where all the docs for clean-css options are described. It solves this issue.

**Comment by bashaus** [comment]
Thanks @shinnn ! +1

**Comment by murphydanger** [comment]
@shinnn is this issue solved, or no?

**Comment by shinnn** [comment]
Not solved.

**Comment by DeadcatDev** [comment]
Still waiting for it :+1:
