### ISSUE TITLE
`clean-css` not updated

### ISSUE THREAD

**Issue by daanvanham** [murphydanger/gulp-minify-css#125]
I ran into an issue for `clean-css`: https://github.com/jakubpawlowicz/clean-css/issues/668. Could the dependency get an update?

**Comment by shinnn** [comment]
https://github.com/murphydanger/gulp-minify-css/issues/122#issuecomment-140342744

**Comment by daanvanham** [comment]
Ah, my bad... Sorry for bothering you with nothing :)

**Comment by shinnn** [comment]
@daanvanham No problem. Thanks for trying to contribute to this project though.
