### ISSUE TITLE
How To Rename File After Minification?

### ISSUE THREAD

**Issue by Amakaruk** [murphydanger/gulp-minify-css#131]
I want to rename my style.css file as style.min.css after running the minify-css task. How should I modify my code?

    // Minify CSS
    gulp.task('minify-css', function() {
      return gulp.src('./dist/css/style.css')
        .pipe(minifyCss({compatibility: 'ie8'}))
        .pipe(gulp.dest('./dist/css'));
    });

**Comment by shinnn** [comment]
https://github.com/murphydanger/gulp-minify-css/issues/53#issuecomment-68443979
