### ISSUE TITLE
Plugin deprecated?

### ISSUE THREAD

**Issue by skoblenick** [murphydanger/gulp-minify-css#135]
Is this plugin deprecated in favor of gulp-cssnano like the npm registry implies? If so can you please update the readme to indicate this.

**Comment by murphydanger** [comment]
Great question! @shinnn did you deprecate the plugin?

**Comment by murphydanger** [comment]
I believe that @shinnn did, in fact, deprecate this plugin. Owing to his wishes, I guess we'll leave it that way.

**Comment by zarko-tg** [comment]
Unsure if that'll do. We got at least one Angular Ionic project (hybrid mobile app) using gulp-minify-css out of the box. Switching to gulp-cssnano added about 5 seconds to the process that is often used continuously on a daily basic / during heavier development.

First impressions anyhow.

**Comment by murphydanger** [comment]
Interesting!

We'll one solution would be to not minimize your css during development,
but even then 5 seconds seems like a long time.

Have you looked at the various options?

**Comment by zarko-tg** [comment]
@murphydanger Certainly, not minimizing the css continuously while developing/saving files is something to consider. Even though we always prefer and tend to run in dev. env as close to prod. env.
Other than that I haven't investigates yet any options related to the issue at hand.

**Comment by murphydanger** [comment]
Just as a thought:

If you are already using [`gulp-autoprefixer`](https://github.com/sindresorhus/gulp-autoprefixer), it may make sense unroll it, and instead use the vanilla versions of [`autoprefixer`](https://github.com/postcss/autoprefixer) and [`cssnano`](https://github.com/ben-eb/cssnano) to build just one [`gulp-postcss`](https://github.com/postcss/gulp-postcss) step.

##### e.g.
```js
gulp.task('build-css', function(){
    var postcss = require('gulp-postcss');
    var autoprefixer = require('autoprefixer');
    var cssnano = require('cssnano');
    
    return gulp.src('./assets/styles/*.css')
        .pipe(postcss([autoprefixer(), cssnano()]))
        .pipe(gulp.dest('./static'));
})
```

**Comment by zarko-tg** [comment]
Not using gulp-autoprefixer as far as I can tell.

The Ionic 1 CLI generates/uses a gulpfile.js for created projects as you can see it here: https://gist.github.com/zarko-tg/9e757ebcfe68dc45218f

In short, it first runs a SASS compiler and then it minimizes. So as it is at present (using gulp-minify-css), you'll get times as these:
```
$ gulp
[12:40:07] Using gulpfile ~/temp/ionic_test/gulpfile.js
[12:40:07] Starting 'sass'...
[12:40:07] Finished 'sass' after 752 ms
[12:40:07] Starting 'default'...
[12:40:07] Finished 'default' after 7.17 μs
```
When using nano() instead of minifyCss(...) in the pipe, I get the following times:
```
$ gulp
[12:45:23] Using gulpfile ~/temp/ionic_test/gulpfile.js
[12:45:23] Starting 'sass'...
[12:45:35] Finished 'sass' after 13 s
[12:45:35] Starting 'default'...
[12:45:35] Finished 'default' after 7.62 μs
```

Not sure if this has to do with Gulp usage or it's some kind of problem with gulp-cssnano. Perhaps @ben-eb can have a look.

If you want to fully tests this case from scratch, you need: ionic start -a ionic_test ionic_test blank

To wrap up, you might want to close this thread and move this or similar discussions over at gulp-cssnano.

**Comment by ben-eb** [comment]
These issues might help in regard to performance discussion, which is a known issue; historically I have prioritised features over performance. Don't think that the gulp wrapper is going to make a whole lot of difference, but any benchmarks you have are welcome.

* v4 refactoring: https://github.com/ben-eb/cssnano/issues/88
* general perf: https://github.com/ben-eb/cssnano/issues/47 & https://github.com/ben-eb/cssnano/issues/7#issuecomment-97240419

**Comment by murphydanger** [comment]
@zarko-tg 

##### Truth 
`cssnano` is *slow*. But this is likely due to all the de-duplication it's doing in the background--I've seen a 10% size reduction in my resulting `css` files. 

##### HOWEVER
If you want to speed things up (at the cost of these great compression benefits), try: `discardDuplicates: false` as an option.

**Comment by Mitranim** [comment]
I believe the deprecation is ill-advised. This plugin is for people who prefer `clean-css` over `cssnano`.

**Comment by murphydanger** [comment]
Just because the plugin is depreciated doesn't mean it doesn't work any more. 

Let's see if `cssnano` improves overtime and if things remain so unpalatable, then we can always _undeprecate_ this package, I suppose.

**Comment by glen-84** [comment]
I also chose `clean-css` over `cssnano` (due to performance), so this is a bit disappointing.

**Comment by dgreene1** [comment]
Yes, since our team recompiles the CSS whenever there is a change to any CSS file, we can't afford to pause for the wait times of cssnano. So I'm going to continue using gulp-minify-css until cssnano improves performance.

**Comment by buschschwick** [comment]
@dgreene1 just out of curiosity what kind of times are you seeing with cssnano? Our team made the jump and don't really see any significant performance impact. Are we talking massive CSS compiling?

**Comment by dgreene1** [comment]
@buschschwick, I believe it was about 60 seconds for cssnano and 30 seconds for gulp-minify-css. If someone wants me to get specific measurements, I can do that.

**Comment by buschschwick** [comment]
@dgreene1 Oh wow. We aren't hitting any sort of times like that, our projects are at _maybe_ 1 to 2 seconds. Interesting!

**Comment by dgreene1** [comment]
Our issues seem to be exacerbated by the fact that we're using a manually generated glob, like:
['file1',
'file2',
//...
'file234']

We have the short term goal of using a wildcard to simply that, but in the meantime we're stuck with a hardcoded list of css files. I'm sure that isn't making cssnano any happier. :/

**Comment by ImBobby** [comment]
Found several ways to use clean-css from the [repo](https://github.com/jakubpawlowicz/clean-css#how-to-use-clean-css-with-build-tools), which is using [gulp-cleancss](https://github.com/mgcrea/gulp-cleancss) or using [vinyl-map](https://github.com/jakubpawlowicz/clean-css/issues/342). Was excited to discover gulp-cleancss but unfortunately the plugin is not maintained and I doubt whether using vinyl-map is a wise move.

**Comment by mikesherov** [comment]
This is an open source, MIT licensed package. Fork the project, republish on npm as gulp-clean-css, and maintain it!

Deprecation means the original maintainer has no interest in maintaining it any further.

**Comment by murphydanger** [comment]
:+1:

**Comment by scniro** [comment]
@ImBobby @skoblenick @zarko-tg @ben-eb @Mitranim @glen-84 @dgreene1 I have forked and published [https://github.com/scniro/gulp-clean-css](gulp-clean-css) as a result of this warning and will maintain the project going forward. All deps including `clean-css` are up to date

**Comment by glen-84** [comment]
@scniro Awesome! Thank you.

**Comment by ImBobby** [comment]
@scniro You're awesome!

**Comment by murphydanger** [comment]
Well this is lovely. I'll go ahead and change the npm plugin deprecation warning to point to you.

Word of advice: don't have @shinnn maintain your project. He'll randomly get mad at you, and suddenly deprecate your plugin. :no_good:
