### ISSUE TITLE
Is the plugin depricated?

### ISSUE THREAD

**Issue by wzup** [murphydanger/gulp-minify-css#136]
I get this warn:
```
npm WARN deprecated gulp-minify-css@1.2.2: Use better "gulp-cssnano" instead. https://github.com/ben-eb/gulp-cssnano
```
Is that true?

**Comment by murphydanger** [comment]
copy of #135

**Comment by scniro** [comment]
@wzup I have forked and published [https://github.com/scniro/gulp-clean-css](gulp-clean-css) as a result of this warning and will maintain the project going forward. All deps including `clean-css` are up to date
