### ISSUE TITLE
Remove deprecation warning

### ISSUE THREAD

**Issue by scniro** [murphydanger/gulp-minify-css#137]
This package is far superior than gulp-cssnano in terms of raw out-of-the-box performance. I swapped for gulp-cssnano on a large project and am experiencing execution times of which are ~20x longer. Perhaps "more advanced optimizations" has it's place, but I will not consider such a package with execution times of that  length.

Deprecating this package based on the vast performance difference does not seem just. cssnano seems to have [documented performance issues](https://github.com/ben-eb/cssnano/issues/47). Since gulp-minify-css uses clean-css, this further seems to reiterate that this package simply should live alongside gulp-cssnano without any deprecation concerns.

**Comment by phazei** [comment]
+1

**Comment by erwstout** [comment]
+1

**Comment by ralf-prescher** [comment]
+1

**Comment by mikesherov** [comment]
This is an open source, MIT licensed package. Fork the project, republish on npm as `gulp-clean-css`, and maintain it!

Deprecation means the original maintainer has no interest in maintaining it any further.

**Comment by scniro** [comment]
done! Nice suggestion btw. Tests and CI are removed for now, coming soon once I get some time, but I definitely plan to actively maintain this under the new name. Feel free to migrate to this for now if you'd like - it'll become more refined/complete in the future as I can work on it - which I am more than excited to do :)
