### ISSUE TITLE
Relative paths rebased incorrectly in v1.1.1

### ISSUE THREAD

**Issue by keeth** [murphydanger/gulp-minify-css#95]
v.1.1.1 (specifically f1758cf / fix for #89) just broke my site unfortunately.  I have a layout like:

assets/styles/icomoon.css
assets/fonts/icomoon.ttf

and icomoon.css has URLs like url('../fonts/icomoon.ttf')

In 1.1.0, my minified CSS had the above relative URL preserved.
In 1.1.1 it is rebased to url('styles/fonts/icomoon.ttf') which does not exist.

For context, I added the following log statement to gulp-minify-css/index.js just before the call to 'new CleanCSS':

    console.log(file.base, file.path, fileOptions);

In 1.1.0 I get:

    styles styles/plugins.css { relativeTo: '/srv/app/web/app/themes/spright/styles' }
    styles styles/editor-style.css { relativeTo: '/srv/app/web/app/themes/spright/styles' }
    styles styles/main.css { relativeTo: '/srv/app/web/app/themes/spright/styles' }

In 1.1.1 I get:

    styles styles/plugins.css { relativeTo: '/srv/app/web/app/themes/spright/styles', target: 'styles' }
    styles styles/editor-style.css { relativeTo: '/srv/app/web/app/themes/spright/styles', target: 'styles' }
    styles styles/main.css { relativeTo: '/srv/app/web/app/themes/spright/styles', target: 'styles' }

Looks like target: 'styles' is the culprit.  LMK if I can provide more info.  Thanks!

**Comment by psirenny** [comment]
I'm having the same issue. The target is set to the folder the css file is processed in but not necessarily output to.

**Comment by shinnn** [comment]
Thanks for reporting.

I found a bug in [the upstream project](https://github.com/jakubpawlowicz/clean-css) so I'll open a new issue about it there.

**Comment by saralkochar** [comment]
+1 for this issue.

**Comment by shinnn** [comment]
I'll update this plugin and release a new version after https://github.com/jakubpawlowicz/clean-css/issues/580 is fixed and clean-css v3.3.0 is released.

**Comment by shinnn** [comment]
FYI you can use a more stable CSS minifier [gulp-cssnano](https://github.com/ben-eb/gulp-cssnano).

**Comment by shinnn** [comment]
https://github.com/jakubpawlowicz/clean-css/issues/580 has been fixed. Still waiting for clean-css v3.3.0 on npm. https://github.com/jakubpawlowicz/clean-css/commit/6eb27badc0321066d085ff41c7e5f8ad73fba3e7#commitcomment-11446875

**Comment by saralkochar** [comment]
You guys are brilliant. I'll test it later today on our environment and will keep you posted if we come across anything unusual. 
Besides, just want to write and say thank-you for the resource. We are a statup and such resources are amazing for us. Hopefully if we get funded, we will make sure to give back tot he community. 

Warmest Regards,
Saral

CEO
Techpacker.com
